"""Initial migration

Revision ID: b07c6ab0606e
Revises: 6fc977e1cf6f
Create Date: 2025-08-03 10:26:02.010490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07c6ab0606e'
down_revision: Union[str, None] = '6fc977e1cf6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addTask_id', table_name='addTask')
    op.drop_index('ix_addTask_title', table_name='addTask')
    op.drop_table('addTask')
    op.drop_table('users')
    op.drop_index('ix_user_login_logs_id', table_name='user_login_logs')
    op.drop_table('user_login_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('login_time', sa.DATETIME(), nullable=True),
    sa.Column('logout_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_login_logs_id', 'user_login_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('addTask',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('priority', sa.VARCHAR(), nullable=False),
    sa.Column('repeat', sa.VARCHAR(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('days_remaining', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('completion_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('modified_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addTask_title', 'addTask', ['title'], unique=False)
    op.create_index('ix_addTask_id', 'addTask', ['id'], unique=False)
    # ### end Alembic commands ###
